### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by essamamdani** [wix-incubator/mjml-react#13] opened 2018-12-19 21:04 UTC
I am having an error when i tried it in Codesandbox. Please assist it why it omits this error.

Could not find module in path: 'uglify-js/lib/utils.js' relative to '/node_modules/uglify-js/tools/node.js'

**Comment by mastertheblaster** [comment] 2018-12-19 22:13
Hi,

Seems related to https://github.com/mjmlio/mjml/issues/1365, checking if we could fix this somehow.
You can install the `mjml` and try importing it `import mjml2html from 'mjml'. As the result you would get exactly same error.

**Comment by mastertheblaster** [comment] 2018-12-20 00:05
Based on the comments inside https://github.com/mjmlio/mjml/issues?q=is%3Aissue+webpack+is%3Aclosed closed issues, the latest mjml is not supported inside browser environment. They do suggest implementing it on a server side. So very sorry, but in best effort we need to identify the root cause and make a PR for the `mjml` itself.

And currently closing this issue, cause it's the problem of underlying project.

**Closed by mastertheblaster** 2018-12-20 00:05 UTC
Labels: question
